### ISSUE TITLE
Jouluteeman teksti ei ole luettava punavihervärisokeille

### ISSUE THREAD

**Issue by ikaros02** [teemupaloniemi/kahvikamera#5]
Voisiko teksti olla vaikkapa mustalla?

**Comment by teemupaloniemi** [comment]
Tausta nyt mustana. Kerran eräs opettaja kertoi minulle "tyylivinkkejä" pukeutumiseen ja hänen sanoin "sininen-musta ja vihreä-musta eivät sovi yhteen" Jatketaan tällä kunnes joku perustelee paremmin.
